groups:
  ldap-wmde:
    label: wmde
    type: wmf-ldap
  ldap-nda:
    label: nda
    type: wmf-ldap
  deployment:
    label: deployment
    type: wmf-ldap-puppet
  wdqs-admins:
    label: wdqs-admins
    type: wmf-ldap-puppet
  analytics-privatedata-users:
    label: analytics-privatedata-users
    type: wmf-ldap-puppet
  analytics-wmde-users:
    label: analytics-wmde-users
    type: wmf-ldap-puppet
  contint-admins:
    label: contint-admins
    type: wmf-ldap-puppet
  contint-docker:
    label: contint-docker
    type: wmf-ldap-puppet
  releasers-wikibase:
    label: releasers-wikibase
    type: wmf-ldap-puppet
  releasers-wikidiff2:
    label: releasers-wikidiff2
    type: wmf-ldap-puppet
  project-deployment-prep:
    label: deployment-prep
    type: wmf-ldap
  project-lizenzhinweisgenerator:
    label: lizenzhinweisgenerator
    type: wmf-ldap
  project-wikidata-dev:
    label: wikidata-dev
    type: wmf-ldap
  project-wikidata-query:
    label: wikidata-query
    type: wmf-ldap
  project-wmde-dashboards:
    label: wmde-dashboards
    type: wmf-ldap
  gerrit-managers:
    label: "Gerrit Managers"
    url: "https://gerrit.wikimedia.org/r/#/admin/groups/119,members"
  phabricator-project-admins:
    label: "Project-Admins"
    url: "https://phabricator.wikimedia.org/project/members/1776/"
  phabricator-wmf-nda:
    label: NDA
    url: "https://phabricator.wikimedia.org/project/members/61/"
  phabricator-security:
    label: Security
    url: "https://phabricator.wikimedia.org/project/members/30/"

columns:
  ldap-magic:
    category: "LDAP magic"
    columns:
      - ldap-wmde
      - ldap-nda
  ldap-puppet:
    category: "LDAP operations-puppet"
    columns:
      - deployment
      - wdqs-admins
      - analytics-privatedata-users
      - analytics-wmde-users
      - contint-admins
      - contint-docker
      - releasers-wikibase
      - releasers-wikidiff2
  ldap-cloud-projects:
    category: "Cloud VPS"
    columns:
      - project-deployment-prep
      - project-lizenzhinweisgenerator
      - project-wikidata-dev
      - project-wikidata-query
      - project-wmde-dashboards
  gerrit:
    category: Gerrit
    columns:
      - gerrit-managers
  phabricator:
    category: Phabricator
    columns:
      - phabricator-project-admins
      - phabricator-wmf-nda
      - phabricator-security
